---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nfs-nginx
  namespace: chamo-app-to-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: nfs-www
        persistentVolumeClaim:
          claimName: nfs-storage
      - image: nginx
        name: nginx
        volumeMounts:
        - name: nfs-www 
          mountPath: /usr/share/nginx/html
