---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fastapi-app-get-kustomize
  namespace: chamo-app-to-apps
spec:
  serviceName: "fastapi-app-get-kustomize"
  replicas: 4
  selector:
    matchLabels:
      app: fastapi-app-get-kustomize
  template:
    metadata:
      labels:
        app: fastapi-app-get-kustomize
    spec:
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.21
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html/
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      storageClassName: nfs-client
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

