---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: chamo
spec:
  type: LoadBalancer
  loadBalancerClass: kube-vip.io/kube-vip-class
  loadBalancerIP: 0.0.0.0
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app.kubernetes.io/name: nginx-deployment
