---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-get-kustomize
  namespace: chamo-app-to-apps
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: fastapi-app-get-kustomize
