---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-get-kustomize
  namespace: chamo-app-to-apps
spec:
  type: LoadBalancer
  loadBalancerIP: "172.18.8.53"
  loadBalancerClass: kube-vip.io/kube-vip-class
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: fastapi-app-get-kustomize
