---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-get-kustomize
  namespace: chamo
spec:
  type: LoadBalancer
  loadBalancerClass: kube-vip.io/kube-vip-class
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
