apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: chamo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      name: nginx
      namespace: chamo
    spec:
      volumes:
      - name: nfs-www
        persistentVolumeClaim:
          claimName: nfs-client
      - image: nginx
        name: nginx
        volumeMounts:
          - name: nfs-www 
            mountPath: /usr/share/nginx/html
