apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: chamo
  labels:
    app: nginx
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 172.18.8.254:5000/fastapi:v1.1
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nfs-www 
            mountPath: /usr/share/nginx/html
      volumes:
        - name: nfs-www
          persistentVolumeClaim:
            claimName: nfs-pvc
