apiVersion: apps/v1
kind: Deployment
metadata:
  name: chamo-deployment
  namespace: chamo
  labels:
    app: nginx
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ghcr.io/alvarolinarescabre/fastapi-app-get-href-from-10-websites:v1.3.0
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nfs-www 
            mountPath: /usr/share/nginx/html
      volumes:
        - name: nfs-www
          persistentVolumeClaim:
            claimName: nfs-pvc
