apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    app: nginx
    namespace: chamo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/mnt/www/"
    server: "172.18.8.254"
    readOnly: false
