apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-volume
  namespace: chamo-app-to-apps
spec:
  storageClassName: csi-hostpath-sc
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.142
    path: "/tmp"
