apiVersion: v1
kind: PersistentVolume
metadata:
  name: csi-hostpath-chamo-app-to-apps
  namespace: chamo-app-to-apps
spec:
  storageClassName: csi-hostpath-sc
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
