kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc
  namespace: chamo
spec:
  selector:
    matchLabels:
      app: nginx
      namespace: chamo
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
