apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-get-href-from-10-websites
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
  type: LoadBalancer
  loadBalancerIP: 172.18.8.52
  externalTrafficPolicy: Cluster
