---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chamo-ingress
  namespace: chamo
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: kong
  rules:
  - host: www.chamo.local 
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: chamo-service
              port:
                number: 80
